# Generated by Django 4.2.6 on 2023-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_corriente',
            name='conta',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='conta_corriente',
            name='tipo_conta',
            field=models.CharField(default='Conta corriente', max_length=15),
        ),
        migrations.AlterField(
            model_name='conta_poupança',
            name='conta',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='conta_poupança',
            name='tipo_conta',
            field=models.CharField(default='Conta poupança', max_length=14),
        ),
    ]
